services:
  mailarchive-app:
    image: s1t5/mailarchiver:latest
    restart: always
    env_file: ../stack.env
    ports:
      - "5000:5000"
    networks:
      - postgres
      - cloudflared
    volumes:
      - ./data-protection-keys:/app/DataProtection-Keys
    depends_on:
      postgres:
        condition: service_healthy


  postgres:
    image: postgres:17-alpine
    restart: always
    env_file: ../stack.env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mailuser -d MailArchiver"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  postgres:
  cloudflared:
    external: true
