services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel run pi-home
    env_file: ../stack.env
    networks:
      - cloudflared
      - proxy

networks:
  cloudflared:
  proxy:
    external: true
